# Generated by Django 4.0.5 on 2022-06-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image_url', models.URLField()),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image_url', models.URLField()),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('running_time_min', models.CharField(max_length=20)),
                ('descriptions', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'films',
            },
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
            options={
                'db_table': 'films_genres',
            },
        ),
        migrations.CreateModel(
            name='FilmOttPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
            options={
                'db_table': 'films_ott_platforms',
            },
        ),
        migrations.CreateModel(
            name='RatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rating_systems',
            },
        ),
        migrations.CreateModel(
            name='OttPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('films', models.ManyToManyField(through='films.FilmOttPlatform', to='films.film')),
            ],
            options={
                'db_table': 'ott_platforms',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('films', models.ManyToManyField(through='films.FilmGenre', to='films.film')),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.AddField(
            model_name='filmottplatform',
            name='ott_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.ottplatform'),
        ),
        migrations.AddField(
            model_name='filmgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.genre'),
        ),
        migrations.CreateModel(
            name='FilmDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.director')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
            options={
                'db_table': 'films_directors',
            },
        ),
        migrations.CreateModel(
            name='FilmCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.country')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
            options={
                'db_table': 'films_countries',
            },
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
            options={
                'db_table': 'films_actors',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='rating_systems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.ratingsystem'),
        ),
        migrations.AddField(
            model_name='director',
            name='films',
            field=models.ManyToManyField(through='films.FilmDirector', to='films.film'),
        ),
        migrations.AddField(
            model_name='country',
            name='films',
            field=models.ManyToManyField(through='films.FilmCountry', to='films.film'),
        ),
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(through='films.FilmActor', to='films.film'),
        ),
    ]
