# Generated by Django 4.0.5 on 2022-06-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='descriptions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='running_time_min',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ottplatform',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ratingsystem',
            name='rate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
