# Generated by Django 4.0.5 on 2022-06-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_actor_image_url_alter_director_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='rating_systems',
            new_name='rating_system',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='films',
        ),
        migrations.RemoveField(
            model_name='country',
            name='films',
        ),
        migrations.RemoveField(
            model_name='director',
            name='films',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='films',
        ),
        migrations.RemoveField(
            model_name='ottplatform',
            name='films',
        ),
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.ManyToManyField(related_name='actors', through='films.FilmActor', to='films.film'),
        ),
        migrations.AddField(
            model_name='country',
            name='film',
            field=models.ManyToManyField(related_name='countries', through='films.FilmCountry', to='films.film'),
        ),
        migrations.AddField(
            model_name='director',
            name='film',
            field=models.ManyToManyField(related_name='directors', through='films.FilmDirector', to='films.film'),
        ),
        migrations.AddField(
            model_name='genre',
            name='film',
            field=models.ManyToManyField(related_name='genres', through='films.FilmGenre', to='films.film'),
        ),
        migrations.AddField(
            model_name='ottplatform',
            name='film',
            field=models.ManyToManyField(related_name='ott_platforms', through='films.FilmOttPlatform', to='films.film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='running_time_min',
            field=models.IntegerField(),
        ),
    ]
