# Generated by Django 4.0.5 on 2022-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_descriptions_film_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='cast',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
