# Generated by Django 4.0.5 on 2022-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_cast_role_filmactor_cast_filmactor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='director',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
