# Generated by Django 4.0.5 on 2022-06-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_actor_image_url_alter_director_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmactor',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.cast'),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.role'),
        ),
    ]
