# Generated by Django 4.0.5 on 2022-06-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='films',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
